// <auto-generated />
using System;
using IdeaManagementProject.Server.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IdeaManagementProject.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330212519_AddCoordinatorNotificationsTable")]
    partial class AddCoordinatorNotificationsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.AcademicYear", b =>
                {
                    b.Property<int>("AcademicYearId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("academic_year_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AcademicYearId"));

                    b.Property<string>("YearName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("year_name");

                    b.HasKey("AcademicYearId");

                    b.HasIndex("YearName")
                        .IsUnique();

                    b.ToTable("AcademicYear", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Attachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attachment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AttachmentId"));

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("content_type");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("file_path");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("original_name");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("uploaded_at");

                    b.HasKey("AttachmentId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Attachment", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Category", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.ClosurePeriod", b =>
                {
                    b.Property<int>("ClosurePeriodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("closure_period_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ClosurePeriodId"));

                    b.Property<int>("AcademicYearId")
                        .HasColumnType("int")
                        .HasColumnName("academic_year_id");

                    b.Property<DateTime>("CommentEndAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("comment_end_at");

                    b.Property<DateTime>("IdeaEndAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("idea_end_at");

                    b.Property<DateTime>("IdeaStartAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("idea_start_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("title");

                    b.HasKey("ClosurePeriodId");

                    b.HasIndex("AcademicYearId");

                    b.ToTable("ClosurePeriod", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("comment_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int")
                        .HasColumnName("author_user_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.HasKey("CommentId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<int?>("QaCoordinatorUserId")
                        .HasColumnType("int")
                        .HasColumnName("qa_coordinator_user_id");

                    b.HasKey("DepartmentId");

                    b.HasIndex("QaCoordinatorUserId");

                    b.ToTable("Department", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Idea", b =>
                {
                    b.Property<int>("IdeaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdeaId"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int")
                        .HasColumnName("author_user_id");

                    b.Property<int>("ClosurePeriodId")
                        .HasColumnType("int")
                        .HasColumnName("closure_period_id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_anonymous");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("title");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("view_count");

                    b.HasKey("IdeaId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("ClosurePeriodId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Idea", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.IdeaCategory", b =>
                {
                    b.Property<int>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int")
                        .HasColumnName("category_id");

                    b.HasKey("IdeaId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("IdeaCategory", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("notification_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("department_name");

                    b.Property<int?>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.Property<string>("IdeaTitle")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("idea_title");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("message");

                    b.Property<int>("RecipientUserId")
                        .HasColumnType("int")
                        .HasColumnName("recipient_user_id");

                    b.Property<string>("StaffName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("staff_name");

                    b.HasKey("NotificationId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IdeaId");

                    b.HasIndex("RecipientUserId");

                    b.ToTable("Notification", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("role_name");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("AcceptedTermsAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("accepted_terms_at");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)")
                        .HasColumnName("password_hash");

                    b.Property<int>("RoleId")
                        .HasColumnType("int")
                        .HasColumnName("role_id");

                    b.HasKey("UserId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Vote", b =>
                {
                    b.Property<int>("VoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("vote_id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("VoteId"));

                    b.Property<int>("IdeaId")
                        .HasColumnType("int")
                        .HasColumnName("idea_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("value");

                    b.HasKey("VoteId");

                    b.HasIndex("UserId");

                    b.HasIndex("IdeaId", "UserId")
                        .IsUnique();

                    b.ToTable("Vote", (string)null);
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Attachment", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Idea", "Idea")
                        .WithMany("Attachments")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.ClosurePeriod", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.AcademicYear", "AcademicYear")
                        .WithMany("ClosurePeriods")
                        .HasForeignKey("AcademicYearId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AcademicYear");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Comment", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.User", "AuthorUser")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Idea", "Idea")
                        .WithMany("Comments")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Department", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.User", "QaCoordinatorUser")
                        .WithMany()
                        .HasForeignKey("QaCoordinatorUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("QaCoordinatorUser");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Idea", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.User", "AuthorUser")
                        .WithMany("Ideas")
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.ClosurePeriod", "ClosurePeriod")
                        .WithMany("Ideas")
                        .HasForeignKey("ClosurePeriodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Department", "Department")
                        .WithMany("Ideas")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AuthorUser");

                    b.Navigation("ClosurePeriod");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.IdeaCategory", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Category", "Category")
                        .WithMany("IdeaCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Idea", "Idea")
                        .WithMany("IdeaCategories")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Notification", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Idea", "Idea")
                        .WithMany("Notifications")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.User", "RecipientUser")
                        .WithMany("Notifications")
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("RecipientUser");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.User", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Vote", b =>
                {
                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.Idea", "Idea")
                        .WithMany("Votes")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IdeaManagementProject.Server.Domain.Entities.User", "User")
                        .WithMany("Votes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Idea");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.AcademicYear", b =>
                {
                    b.Navigation("ClosurePeriods");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Category", b =>
                {
                    b.Navigation("IdeaCategories");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.ClosurePeriod", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Department", b =>
                {
                    b.Navigation("Ideas");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Idea", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("Comments");

                    b.Navigation("IdeaCategories");

                    b.Navigation("Notifications");

                    b.Navigation("Votes");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("IdeaManagementProject.Server.Domain.Entities.User", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Ideas");

                    b.Navigation("Notifications");

                    b.Navigation("Votes");
                });
#pragma warning restore 612, 618
        }
    }
}
